### ISSUE TITLE
USB Serial Device not being recognised/loaded

### ISSUE THREAD

**Issue by gazzer82** [nerves-project/nerves_system_rpi4#143]
### Environment

* Elixir version (`elixir -v`): Elixir 1.12.3 (compiled with Erlang/OTP 24)
* Nerves environment: (`mix nerves.env --info`)
```
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.8.5
  Type:        toolchain_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_aarch64_nerves_linux_gnu
  Vsn:         1.5.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_br
  Vsn:         1.18.4
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_rpi4
  Vsn:         1.18.2
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, [make_args: ["source", "all", "legal-info"]]}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   rpi4
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi4
  toolchain:  /Users/*/.nerves/artifacts/nerves_toolchain_aarch64_nerves_linux_gnu-darwin_arm-1.5.0
  system:     /Users/*/.nerves/artifacts/nerves_system_rpi4-portable-1.18.2
  app:        .

|nerves_bootstrap| Loadpaths End
```
* Additional information about your host, target hardware or environment that
  may help

Building on MacOS 12.1 on M1, target is a Pi4.

### Current behavior

I have a Plugable USB-RS232 adaptor connected to the Pi on USB, it contains a Prolific PL2303 chip. It is detected as follows from dmesg:

```
[ 4032.061149] usb 1-1.1: new full-speed USB device number 5 using xhci_hcd
[ 4032.165601] usb 1-1.1: New USB device found, idVendor=067b, idProduct=2303, bcdDevice= 4.00
[ 4032.165616] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 4032.165625] usb 1-1.1: Product: USB-Serial Controller D
[ 4032.165635] usb 1-1.1: Manufacturer: Prolific Technology Inc. 
```
However it is not mapped to a serial port as I would expect. If I do the same on Raspbian I get the following additional lines when attaching it to the system:

```
[ 1439.746797] pl2303 1-1.3:1.0: pl2303 converter detected
[ 1439.763784] usb 1-1.3: pl2303 converter now attached to ttyUSB0
```

I'm pretty new to Nerves and not 100% sure on all the moving parts, but the driver for this I think it included in the USB_SERIAL module which is compiled as part of the image?

### Expected behavior

The device to be detected and then mapped to a serial port on the device.

**Comment by fhunleth** [comment]
Thanks for posting about this. This one is so common that I was surprised it wasn't enabled already. I fixed it in the PR. This won't be in the official release for a while. If you want to use it, you can make a custom system with the change. Another option would be to use of of the other adapters that I mentioned on your Elixir Forum post.
