### ISSUE TITLE
Raspberry Pi Global Shutter Camera

### ISSUE THREAD

**Issue by entone** [nerves-project/nerves_system_rpi4#220]
Hey team! Been a while :) Was wondering if there are any plans to add support for the new-ish Global Shutter camera?

Looks like we would need to add the imx296 overlay. I'm not positive where those are sourced from.

**Comment by fhunleth** [comment]
Hi @entone!

Welcome back!

If we're lucky, adding the global shutter camera should be similar to what was done at https://github.com/nerves-project/nerves_system_rpi4/commit/67ac46db2f8ca54cfdeeaa4b73dc66f29e18977a. If they're not in the version of Linux we're using, updating to the latest isn't hard. Just let me know. I could probably add them real quick when I get some free time (not long).

**Comment by entone** [comment]
Great, I was looking at that commit for a path forward. I'm building the rpi4 firmware now for a local build and will give it a shot, and open a PR. If an updated version of Linux is needed I may need some help.

**Comment by entone** [comment]
#221 opened

**Comment by fhunleth** [comment]
Fixed in #221
