### ISSUE TITLE
[bug / v1.11.0] Erlang VM not started

### ISSUE THREAD

**Issue by jsimmonds2** [nerves-project/nerves_system_rpi4#30]
### Environment

* Elixir version (`elixir -v`):

Erlang/OTP 22 [erts-10.5.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
Elixir 1.9.2 (compiled with Erlang/OTP 22)

* Nerves environment: (`mix nerves.env --info`)
```
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_rpi4
  Vsn:         1.11.0
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.3.1
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_br
  Vsn:         1.11.0
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.7.1
  Type:        toolchain_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   rpi4
  MIX_ENV:      prod

|nerves_bootstrap| Environment Variable List
  target:     rpi4
  toolchain:  /home/jhs/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.3.1
  system:     /home/jhs/.nerves/artifacts/nerves_system_rpi4-portable-1.11.0
  app:        /home/jhs/src/jsimmonds2/RasPi3BPlus/Blinkers/Nerves/fb2

|nerves_bootstrap| Loadpaths End
```

* Additional information about your host, target hardware or environment that
  may help

**nerves_system_rpi4 v1.10.2** worked correctly, repeatably.

### Current behavior

Boot hangs here :

![image](https://user-images.githubusercontent.com/1224439/77134728-6179f580-6abc-11ea-8a19-ca0a3fd2fe58.png)

### Expected behavior

Erlang VM is started successfully and base app runs.

**Comment by mobileoverlord** [comment]
I was able to reproduce this locally with the downloaded artifact. I’m building a clean system to test.
