### ISSUE TITLE
Camera Support

### ISSUE THREAD

**Issue by osterwood** [nerves-project/nerves_system_rpi4#45]
### Environment

* Elixir version:
```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.10.4 (compiled with Erlang/OTP 23)
```

* Nerves environment:
```
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_br
  Vsn:         1.12.0
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_rpi4
  Vsn:         1.12.1
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.7.2
  Type:        toolchain_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.3.2
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}
```
* Additional information about your host, target hardware or environment that
  may help

### Current behavior

I'm building an application on top of [Picam](https://github.com/elixir-vision/picam) and it works (e.g. I can read from an attached camera) on a RPI3, but on a RPI4 the camera hardware is non-functional / not-detected.

### Expected behavior

The README says that cameras are supported, has that been verified?  I've got a new RPI4 incoming to see if this is reproducible on a second board.

**Comment by fhunleth** [comment]
I tried the camera once and it worked, but that was a really long time ago. I've been pulling upstream changes in this area and it's entirely possible that one of them broke Picam. 

Do you have any clues? Or it's like it doesn't work and doesn't give any messages?

**Comment by osterwood** [comment]
Thanks for the reply!  The error from Picam is 

```
iex(1)> Picam.Camera.start_link            
{:error, {:already_started, #PID<0.1630.0>}}
iex(2)> File.write!(Path.join(System.tmp_dir!, "frame.jpg"), Picam.next_frame)
** (exit) exited in: GenServer.call(Picam.FakeCamera, :next_frame, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.10.4) lib/gen_server.ex:1013: GenServer.call/3
```

`already_started` happens on the 3 and 4 due to the software I've loaded.  I intentionally don't have a FakeCamera enabled.  If I enable one, I get fake output.  

Looking at dmesg output doesn't have any obvious errors, both the PI 3 and PI 4 have this:

```
bcm2835-v4l2: V4L2 device registered as video0 - stills mode > 1280x720
bcm2835-v4l2: Broadcom 2835 MMAL video capture ver 0.0.2 loaded.
```

and there is a `/dev/video0` device on both systems (along with video10, video11, video12 on the PI 4).  

Any ideas on how to dive deeper into this?

**Comment by osterwood** [comment]
Interestingly, if I stop the nerves software, I am able to run `raspistill` and save a JPG on the PI 4

```
iex> Application.stop(:camera)
iex> Application.stop(:picam) 
iex> System.cmd("/usr/bin/raspistill", ["-v", "-o", "/tmp/image.jpg"], stderr_to_stdout: true)
```
Output is
```
{"\"raspistill\" Camera App (commit 42df6e3e571c)
Camera Name ov5647
Width 2592, Height 1944, filename /tmp/image.jpg
Using camera 0, sensor mode 0
GPS output Disabled
Quality 85, Raw no
Thumbnail enabled Yes, width 64, height 48, quality 35
Time delay 5000, Timelapse 0
Link to latest frame enabled  no
Full resolution preview No
Capture method : Single capture
Preview Yes, Full screen Yes
Preview window 0,0,1024,768
Opacity 255
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 0, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Flicker Avoid Mode 'off'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
Camera component done
Encoder component done
Starting component connection stage
Connecting camera preview port to video render.
Connecting camera stills port to encoder input port
Opening output file /tmp/image.jpg
Enabling encoder output port
Starting capture -1
Finished capture -1
Closing down
Close down completed, all components disconnected, disabled and destroyed",
 0}
```

**Comment by fhunleth** [comment]
Could you `rm -fr _build` and try again?

Code that does this, https://github.com/elixir-vision/picam/blob/master/lib/picam.ex#L7, is notorious for causing confusion. It sets the choice of using `FakeCamera` at compile time and Elixir doesn't know to recompile it when you change your `config.exs`. The Picam code needs to be fixed so that `Application.get_env(:picam, :camera, Picam.Camera)` is called at runtime.

We should fix this, but first I want to make sure that what I'm telling you is the root cause. If you run into any issues, feel free to ping me on the Elixir Lang slack and we can figure out a time to do joint debug and knock this off and get a PR over to picam so it never happens again.

**Comment by osterwood** [comment]
Deleting `_build` and rebuilding worked!  All is well on the PI 4.

Thanks for the help in diagnosing this issue.

**Comment by fhunleth** [comment]
Great! Thanks for following up.
