### ISSUE TITLE
v1.12.2 still looks for fixup4.dat 

### ISSUE THREAD

**Issue by jsimmonds2** [nerves-project/nerves_system_rpi4#58]
### Environment

* Elixir version (`elixir -v`):

Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 23)

* Nerves environment: (`mix nerves.env --info`)

```
|nerves_bootstrap| Environment Package List
  Pkg:         nerves_system_rpi4
  Vsn:         1.12.2
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.7.2
  Type:        toolchain_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.3.2
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_br
  Vsn:         1.12.4
  Type:        system_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   rpi4
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi4
  toolchain:  /home/jhs/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.3.2
  system:     /home/jhs/.nerves/artifacts/nerves_system_rpi4-portable-1.12.2
  app:        /home/jhs/src/jsimmonds2/RasPi3BPlus/Blinkers/Nerves/fb2

|nerves_bootstrap| Loadpaths End
```

* Additional information about your host, target hardware or environment that
  may help

### Current behavior

Include errors, stacktraces, screenshots or code that may help us reproduce the
issue.
```
Building /home/jhs/src/jsimmonds2/RasPi3BPlus/Blinkers/Nerves/fb2/_build/rpi4/rpi4_dev/nerves/images/fb2.fw...
fwup: can't open path '/home/jhs/.nerves/artifacts/nerves_system_rpi4-portable-1.12.2/images/rpi-firmware/fixup4.dat' in file-resource 'fixup4.dat'
** (Mix) Nerves encountered an error. %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: true}

[jhs@f32v-on-comet fb2]$
```

### Expected behavior

Clean firmware build ( as previously when using **nerves_system_rpi4 v1.12.1**

**Comment by fhunleth** [comment]
Do you have the `fwup.conf` overridden? The official one doesn't have any references to `fixup4.dat`.

**Comment by jsimmonds2** [comment]
Ah-Hah ! That was the question to ask. Thanks **so** much !

[ Left over from the heady days of new-born true RPi4B support 🙂 ]

**Thanks again** @fhunleth for your _**kind patience**_.  ( did I miss a warning in the 1.12.2 Release Notes ? )

**Comment by fhunleth** [comment]
No problem. 

You're right. I neglected to mention that file rename is the CHANGELOG.md. I added a note in #59. Thanks for letting me know.
