### ISSUE TITLE
rpi3 to rpi4 project upgrade failure

### ISSUE THREAD

**Issue by jsimmonds2** [nerves-project/nerves_system_rpi4#6]
### Environment

* Elixir version (`elixir -v`):

Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.9.0 (compiled with Erlang/OTP 22)

* Nerves environment: (`mix nerves.env --info`)
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_br
  Vsn:         1.8.5
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_rpi4
  Vsn:         1.8.2
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.2.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.6.0
  Type:        toolchain_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   rpi4
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi4
  toolchain:  /home/jhs/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-linux_x86_64-1.2.0
  system:     /home/jhs/.nerves/artifacts/nerves_system_rpi4-portable-1.8.2
  app:        /home/jhs/src/RasPi3BPlus/Blinkers/Nerves/fb2

|nerves_bootstrap| Loadpaths End

* Additional information about your host, target hardware or environment that
  may help

Just taking a simple project that makes working firmware for rpi3 and changing target to rpi4 with this **`git diff`**

![Screenshot from 2019-08-06 21-53-13](https://user-images.githubusercontent.com/1224439/62538957-61174c00-b897-11e9-8c09-92a6df3395f8.png)

### Current behavior

Include errors, stacktraces, screenshots or code that may help us reproduce the
issue.

![Screenshot from 2019-08-06 22-15-06](https://user-images.githubusercontent.com/1224439/62539279-3083e200-b898-11e9-803c-fa3101c71120.png)

### Expected behavior

Nice firmware file that I can try out in my shiny new RPi4  :)

**Comment by fhunleth** [comment]
Is the project overriding the `fwup.conf` file? The reason I ask is that `fixup.dat` isn't used on the RPi4. It got renamed to `fixup4.dat`. There's a similar change with `start.elf` going to `start4.elf`. The `config.txt` and device tree overlay files also changed.

I think it would be useful to compare the `fwup.conf` file that you have with https://github.com/nerves-project/nerves_system_rpi4/blob/master/fwup.conf. If I remember right, it should a be a bunch of renames and the device tree file.

**Comment by jsimmonds2** [comment]
_**Many thanks**_ for the help !
Yes, my little project is indeed overriding `fwup.conf` . . simply to install the `spi1-3cs` overlay.
Happy now :)

**Comment by jsimmonds2** [comment]
( don't know whether comments on Closed Issues reach anyone . .  but, for the record, . . )
**_Thanks_** to the **Nerves core team** for providing Raspberry Pi 4 Model B support in Nerves so quickly !

I'm now busy fixing code with silly blind time-delays in initializing an I2C device 😮 because of the extra speed of the RPi4B vs the RPi3B+

**Comment by fhunleth** [comment]
We get an email, but they're real easy to miss since we're not being reminded by an open issue.

Thanks for letting us know. The RPi4 port took me longer than I was expecting, and it makes me happy that it's working. After ElixirConf US, I hope to start upgrading my Raspberry Pi projects too.
